//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VpnCard.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>6475</string>
  <string>8170</string>
  <string>1770</string>
  <string>8559</string>
  <string>9388</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection A {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["A"]));
            }
            set {
                this["A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>8626</string>
  <string>6647</string>
  <string>7480</string>
  <string>9220</string>
  <string>9232</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection B {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["B"]));
            }
            set {
                this["B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>5683</string>
  <string>6445</string>
  <string>1538</string>
  <string>3558</string>
  <string>4690</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection C {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["C"]));
            }
            set {
                this["C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>3126</string>
  <string>8289</string>
  <string>8253</string>
  <string>7746</string>
  <string>0679</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection D {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["D"]));
            }
            set {
                this["D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>7067</string>
  <string>0946</string>
  <string>9662</string>
  <string>3631</string>
  <string>9034</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection E {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["E"]));
            }
            set {
                this["E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>1775</string>
  <string>5569</string>
  <string>4719</string>
  <string>3685</string>
  <string>0014</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection F {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["F"]));
            }
            set {
                this["F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>5220</string>
  <string>1506</string>
  <string>2704</string>
  <string>6344</string>
  <string>0264</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection G {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["G"]));
            }
            set {
                this["G"] = value;
            }
        }
    }
}
